In [27]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
%matplotlib inline

dataset = pd.read_csv("C:/Users/M.Naufal/Desktop/testing/test.csv")  

dataset.shape  
dataset.head()  



Unnamed: 0          0          1          2          3          4  \
0        6250 -18.533161 -17.300008 -17.946638 -18.778949 -16.717009   
1        3487 -16.045252 -13.502484  -9.362442  -6.484350  -8.684005   
2         487 -18.074761 -18.489622 -17.979468 -17.089028 -17.256001   
3        2381 -14.989205 -12.663454 -12.758900 -12.473405 -11.537112   
4        2689 -19.691096 -18.994305 -19.307949 -18.766517 -18.449793   

           5          6          7          8  ...    186  187  188  189  190  \
0 -15.957606 -16.168395 -15.031891 -15.520220  ...    0.0  0.0  0.0  0.0  0.0   
1 -11.524328  -9.506710 -10.628959 -12.290954  ...    0.0  0.0  0.0  0.0  0.0   
2 -16.562114 -15.466078 -17.455484 -16.573877  ...    0.0  0.0  0.0  0.0  0.0   
3 -11.008978 -11.764417 -13.219886 -14.947768  ...    0.0  0.0  0.0  0.0  0.0   
4 -17.932033 -16.730863 -16.111133 -17.220508  ...    0.0  0.0  0.0  0.0  0.0   

   191  192  193  194  class  
0  0.0  0.0  0.0  0.0    NEU  
1  0.0  0.0  0.0  0.0    ANG  
2  0.0  0.0  0.0  0.0    DIS  
3  0.0  0.0  0.0  0.0    DIS  
4  0.0  0.0  0.0  0.0    DIS  

[5 rows x 197 columns]

In [28]:
X = dataset.drop('class', axis=1)  
y = dataset['class']

from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)  

from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(X_train, y_train)  

y_pred = classifier.predict(X_test) 




In [29]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  

[[104  37  31  35  31  20]
 [ 25  63  40  28  31  54]
 [ 37  54  41  46  36  45]
 [ 42  40  49  54  41  36]
 [ 25  39  42  38  44  37]
 [ 19  49  38  28  44  66]]
             precision    recall  f1-score   support

        ANG       0.41      0.40      0.41       258
        DIS       0.22      0.26      0.24       241
        FEA       0.17      0.16      0.16       259
        HAP       0.24      0.21      0.22       262
        NEU       0.19      0.20      0.19       225
        SAD       0.26      0.27      0.26       244

avg / total       0.25      0.25      0.25      1489

